pipeline {
  agent any

  tools {
    maven 'Maven_3'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        dir('hello-devops') {
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }

    stage('Test') {
      steps {
        dir('hello-devops') {
          sh 'mvn -B test'
        }
      }
    }

    stage('Archive') {
      steps {
        archiveArtifacts artifacts: 'hello-devops/target/*.jar', fingerprint: true
      }
    }
  }
}
